### ISSUE TITLE
Failed resolution of: Lorg/ietf/jgss/Oid;

### ISSUE THREAD

**Issue by Jomme5** [AgNO3/jcifs-ng#49] opened 2018-02-19 21:31 UTC
Android studio - device: Android 7.0
on `NtlmPasswordAuthentication auth = new NtlmPasswordAuthentication(...)` this happens: 

FATAL EXCEPTION: main
                                                                          Process: com.cornmo.moprac.moprac, PID: 26084
                                                                          java.lang.NoClassDefFoundError: Failed resolution of: Lorg/ietf/jgss/Oid;
                                                                              at jcifs.smb.NtlmContext.<clinit>(NtlmContext.java:50)
                                                                              at jcifs.smb.NtlmPasswordAuthentication.createContext(NtlmPasswordAuthentication.java:234)
                                                                              at jcifs.smb.SmbSessionImpl.sessionSetupSMB1(SmbSessionImpl.java:785)
                                                                              at jcifs.smb.SmbSessionImpl.sessionSetup(SmbSessionImpl.java:466)
                                                                              at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:358)
                                                                              at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:336)
                                                                              at jcifs.smb.SmbTreeImpl.treeConnect(SmbTreeImpl.java:600)
                                                                              at jcifs.smb.SmbTreeConnection.connectTree(SmbTreeConnection.java:606)
                                                                              at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:560)
                                                                              at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:481)
                                                                              at jcifs.smb.SmbTreeConnection.connect(SmbTreeConnection.java:457)
                                                                              at jcifs.smb.SmbTreeConnection.connectWrapException(SmbTreeConnection.java:418)
                                                                              at jcifs.smb.SmbFile.ensureTreeConnected(SmbFile.java:543)
                                                                              at jcifs.smb.SmbFileInputStream.<init>(SmbFileInputStream.java:96)
                                                                              at jcifs.smb.SmbFileInputStream.<init>(SmbFileInputStream.java:71)
                                                                              at com.cornmo.moprac.moprac.Headof$1.onClick(Headof.java:58)
                                                                              at android.view.View.performClick(View.java:5612)
                                                                              at android.view.View$PerformClick.run(View.java:22288)
                                                                              at android.os.Handler.handleCallback(Handler.java:751)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                              at android.os.Looper.loop(Looper.java:154)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:6123)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
                                                                           Caused by: java.lang.ClassNotFoundException: Didn't find class "org.ietf.jgss.Oid" on path: DexPathList[[zip file "/data/app/com.cornmo.moprac.moprac-2/base.apk", zip file "/data/app/com.cornmo.moprac.moprac-2/split_lib_dependencies_apk.apk", zip file "/data/app/com.cornmo.moprac.moprac-2/split_lib_slice_0_apk.apk", zip file "/data/app/com.cornmo.moprac.moprac-2/split_lib_slice_1_apk.apk", zip file "/data/app/com.cornmo.moprac.moprac-2/split_lib_slice_2_apk.apk", zip file "/data/app/com.cornmo.moprac.moprac-2/split_lib_slice_3_apk.apk", zip file "/data/app/com.cornmo.moprac.moprac-2/split_lib_slice_4_apk.apk", zip file "/data/app/com.cornmo.moprac.moprac-2/split_lib_slice_5_apk.apk", zip file "/data/app/com.cornmo.moprac.moprac-2/split_lib_slice_6_apk.apk", zip file "/data/app/com.cornmo.moprac.moprac-2/split_lib_slice_7_apk.apk", zip file "/data/app/com.cornmo.moprac.moprac-2/split_lib_slice_8_apk.apk", zip file "/data/app/com.cornmo.moprac.moprac-2/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.cornmo.moprac.moprac-2/lib/arm, /system/lib, /vendor/lib]]
                                                                              at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                              at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                                                                              at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                              at jcifs.smb.NtlmContext.<clinit>(NtlmContext.java:50) 
                                                                              at jcifs.smb.NtlmPasswordAuthentication.createContext(NtlmPasswordAuthentication.java:234) 
                                                                              at jcifs.smb.SmbSessionImpl.sessionSetupSMB1(SmbSessionImpl.java:785) 
                                                                              at jcifs.smb.SmbSessionImpl.sessionSetup(SmbSessionImpl.java:466) 
                                                                              at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:358) 
                                                                              at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:336) 
                                                                              at jcifs.smb.SmbTreeImpl.treeConnect(SmbTreeImpl.java:600) 
                                                                              at jcifs.smb.SmbTreeConnection.connectTree(SmbTreeConnection.java:606) 
                                                                              at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:560) 
                                                                              at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:481) 
                                                                              at jcifs.smb.SmbTreeConnection.connect(SmbTreeConnection.java:457) 
                                                                              at jcifs.smb.SmbTreeConnection.connectWrapException(SmbTreeConnection.java:418) 
                                                                              at jcifs.smb.SmbFile.ensureTreeConnected(SmbFile.java:543) 
                                                                              at jcifs.smb.SmbFileInputStream.<init>(SmbFileInputStream.java:96) 
                                                                              at jcifs.smb.SmbFileInputStream.<init>(SmbFileInputStream.java:71) 
                                                                              at com.cornmo.moprac.moprac.Headof$1.onClick(Headof.java:58) 
                                                                              at android.view.View.performClick(View.java:5612) 
                                                                              at android.view.View$PerformClick.run(View.java:22288) 
                                                                              at android.os.Handler.handleCallback(Handler.java:751) 
                                                                              at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                              at android.os.Looper.loop(Looper.java:154) 
                                                                              at android.app.ActivityThread.main(ActivityThread.java:6123) 
                                                                              at java.lang.reflect.Method.invoke(Native Method) 
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867) 
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)

**Comment by mbechler** [comment] 2018-02-24 09:08
Duplicate of #20

**Closed by mbechler** 2018-02-24 09:08 UTC
