### ISSUE TITLE
smb url works with jcifs, won't authenticate with jcifs-ng 

### ISSUE THREAD

**Issue by manithree** [AgNO3/jcifs-ng#46] opened 2018-02-16 03:58 UTC
I have some applications that read and write files from a Hitachi HNAS share with jcifs.  Right now, the shares are SMB1 only, but they need to change to SMB2 only, so I'm looking to replace jcifs with jcifs-ng.
I'm using some sample code that just creates an SmbFile and then calls .exists() on it.  The url looks (something) like this:
smb://;user:pass@10.xx.xx.xx/x3vtest03/directory
There's no domain, and jcifs won't authenticate without the semicolon.  I've tried with and without the semicolon, but jcifs-ng always throws an exception on the exists() call saying bad user name or password.
If I just create the SmbFile with the one parameter constructor (String url), according to the logs, it was trying to authenticate as GUEST, and that won't work, so I tried setting jcifs.smb.client.domain, username, and password, then:
    BaseContext bc = new BaseContext(new PropertyConfiguration(System.getProperties()));
    SmbResource sr = bc.get("smb://;***:****@10.xx.xx.xx/x3vtest03/test-r/");
    if (sr.exists()) // throws
And
    NtlmPasswordAuthentication creds = new NtlmPasswordAuthentication(bc, "*****:+++++");
    CIFSContext ct = bc.withCredentials(creds);
    SmbFile test1 = new SmbFile("smb://;*****:+++++@10.xx.xx.xx/x3vtest03/test-r/", ct);b
    System.out.println("test1 exists: " + test1.exists()); // throws

But all I get is:
jcifs.smb.SmbAuthException: Logon failure: unknown user name or bad password.

I'm new to jcifs-ng, and this could all be user error, but I'm running out of ideas.

Thanks

**Comment by mbechler** [comment] 2018-02-17 08:47
I guess you are trying the master branch? There was a bug that I introduced working on #36 which broke NTLM authentication using the legacy credential type (NtlmPasswordAuthentication).

In general, specifying the credentials in the URL is only implemented for the deprecated legacy constructors (SmbFile(String), SmbFile(URL)).

If you are using master, the preferred way to specify credentials would be something like
```
CIFSContext baseCtx =  new BaseContext(new PropertyConfiguration(System.getProperties()));
CIFSContext userCtx = baseCtx.withCredentials(
    new NtlmPasswordAuthentication("username", "password")
);
SmbResource r = userCtx.get("smb://10.xx.xx.xx/x3vtest03/test-r/");
r.exists();
```

**Comment by manithree** [comment] 2018-02-17 15:58
Actually, I forgot to mention I'm using the 2.0.4 release.  I changed my code to be logically equivalent to yours (I think):

            BaseContext bc = new BaseContext(new PropertyConfiguration(System.getProperties()));
            //NtlmPasswordAuthentication creds = new NtlmPasswordAuthentication(bc, "xxxxx:****");
            NtlmPasswordAuthentication creds = new NtlmPasswordAuthentication(bc, "", "xactsites", "wwwdot");
            CIFSContext ct = bc.withCredentials(creds);
            SmbResource sr = ct.get("smb://;xxxxx:****@10.xx.xx.xx/x3vtest03/test-r/");
            if (sr.exists()) // throws


But I still get:

[DEBUG] 2018-02-17 08:45:34.720 [Thread-0] SmbSessionImpl - Session setup failed
jcifs.smb.SmbAuthException: Logon failure: unknown user name or bad password.
        at jcifs.smb.SmbTransportImpl.checkStatus(SmbTransportImpl.java:1325) ~[jcifs-ng-2.0.4.jar:?]

I can't get mine to compile with a NtlmPasswordAuthentication(String, String) like your example, but I tried both the ones in my example, and they both throw the same exception. I tried with an empty string and null for the domain.  I'm out of ideas again.  Thanks for your response.

**Comment by mbechler** [comment] 2018-02-17 16:28
Except that the credentials from _smb://;xxxxx:****@10.xx.xx.xx/x3vtest03/test-r/_ won't be used, but  "xactsites":"wwwdot" instead - I think your latest code should work. Do you still see that trying to authenticate as GUEST?

Yes, my example was for master.

**Comment by manithree** [comment] 2018-02-17 20:12
No, the log shows the correct user name. Would you please delete the credentials I accidentally didn't sanitize from my previous message?  Thanks.

Still get the same exception.

**Comment by manithree** [comment] 2018-02-17 22:17
I built a jar from the master branch (pulled this morning), and I now get a different error:
[DEBUG] 2018-02-17 15:09:45.486 [Thread-0] SmbTransportImpl - Establishing new session SmbSession[credentials=UUUUUU,targetHost=10.xx.xx.xx,targetDomain=null,uid=0,connectionState=0,usage=1] on Transport0
[DEBUG] 2018-02-17 15:09:45.488 [Thread-0] SmbTreeImpl - treeConnect: unc=\\10.xx.xx.xx\X3VTEST03,service=?????
[DEBUG] 2018-02-17 15:09:45.490 [Thread-0] SmbSessionImpl - sessionSetup: UUUUUU
[DEBUG] 2018-02-17 15:09:45.490 [Thread-0] SmbSessionImpl - Extended security negotiated
[DEBUG] 2018-02-17 15:09:45.490 [Thread-0] SmbSessionImpl - Remote host is 10.xx.xx.xx
[DEBUG] 2018-02-17 15:09:45.620 [Thread-0] NtlmPasswordAuthenticator - Have initial token NegTokenInit[flags=0,mechs=[1.2.840.48018.1.2.2, 1.3.6.1.4.1.311.2.2.10],mic=null]
[DEBUG] 2018-02-17 15:09:45.626 [Thread-0] SmbTransportImpl - Breaking on error SmbComSessionSetupAndXResponse[command=SMB_COM_SESSION_SETUP_ANDX,received=true,errorCode=More data is available.,flags=0x0098,flags2=0xC801,signSeq=0,tid=0,pid=56530,uid=1,mid=1,wordCount=4,byteCount=361,andxCommand=0xFF,andxOffset=404,isLoggedInAsGuest=false,nativeOs=Hitachi NAS Platform 12.7.4221.12,nativeLanMan=Hitachi NAS Platform 12.7.4221.12,primaryDomain=]
[DEBUG] 2018-02-17 15:09:45.705 [Thread-0] NtlmContext - Sign key is
[DEBUG] 2018-02-17 15:09:45.705 [Thread-0] NtlmContext - Verify key is 
[DEBUG] 2018-02-17 15:09:45.705 [Thread-0] NtlmContext - Seal key is 
[DEBUG] 2018-02-17 15:09:45.705 [Thread-0] NtlmContext - Server seal key is 
[DEBUG] 2018-02-17 15:09:45.705 [Thread-0] NtlmContext - Digest 
[DEBUG] 2018-02-17 15:09:45.705 [Thread-0] NtlmContext - Truncated
[DEBUG] 2018-02-17 15:09:45.705 [Thread-0] NtlmContext - Encrypted
[DEBUG] 2018-02-17 15:09:45.706 [Thread-0] SpnegoContext - Out Mech list 
[DEBUG] 2018-02-17 15:09:45.706 [Thread-0] SpnegoContext - Out Mech list encoded 
[DEBUG] 2018-02-17 15:09:45.706 [Thread-0] SpnegoContext - Out Mech list MIC 
[WARN ] 2018-02-17 15:09:45.706 [Thread-0] SmbTransportImpl - Disconnecting transport while still in use Transport0[0.0.0.0<00>/10.xx.xx.xx:445,state=5,signingEnforced=false,usage=5]: [SmbSession[credentials=UUUUUU,targetHost=10.xx.xx.xx,targetDomain=null,uid=0,connectionState=1,usage=3]]
[DEBUG] 2018-02-17 15:09:45.706 [Thread-0] SmbTransportImpl - Disconnecting transport Transport0[0.0.0.0<00>/10.xx.xx.xx:445,state=5,signingEnforced=false,usage=5]
[DEBUG] 2018-02-17 15:09:45.707 [Thread-0] SmbTransportPoolImpl - Removing transport connection Transport0[0.0.0.0<00>/10.xx.xx.xx:445,state=5,signingEnforced=false,usage=5] (1506923721)
[DEBUG] 2018-02-17 15:09:45.707 [Thread-0] SmbSessionImpl - Session setup failed
jcifs.smb.SmbUnsupportedOperationException: Operation is not supported with the negotiated capabilities
        at jcifs.smb.SmbTransportImpl.checkStatus(SmbTransportImpl.java:1359) ~[jcifs-ng-2.1.0-SNAPSHOT.jar:?]
        at jcifs.smb.SmbTransportImpl.checkStatus(SmbTransportImpl.java:1540) ~[jcifs-ng-2.1.0-SNAPSHOT.jar:?]
        at jcifs.smb.SmbTransportImpl.sendrecv(SmbTransportImpl.java:1007) ~[jcifs-ng-2.1.0-SNAPSHOT.jar:?]
        at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1506) ~[jcifs-ng-2.1.0-SNAPSHOT.jar:?]
        at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1470) ~[jcifs-ng-2.1.0-SNAPSHOT.jar:?]
        at jcifs.smb.SmbSessionImpl.sessionSetupSMB1(SmbSessionImpl.java:1017) ~[jcifs-ng-2.1.0-SNAPSHOT.jar:?]
        at jcifs.smb.SmbSessionImpl.sessionSetup(SmbSessionImpl.java:480) [jcifs-ng-2.1.0-SNAPSHOT.jar:?]
        at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:363) [jcifs-ng-2.1.0-SNAPSHOT.jar:?]
        at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:341) [jcifs-ng-2.1.0-SNAPSHOT.jar:?]
        at jcifs.smb.SmbTreeImpl.treeConnect(SmbTreeImpl.java:607) [jcifs-ng-2.1.0-SNAPSHOT.jar:?]
        at jcifs.smb.SmbTreeConnection.connectTree(SmbTreeConnection.java:609) [jcifs-ng-2.1.0-SNAPSHOT.jar:?]
        at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:563) [jcifs-ng-2.1.0-SNAPSHOT.jar:?]
        at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:484) [jcifs-ng-2.1.0-SNAPSHOT.jar:?]
        at jcifs.smb.SmbTreeConnection.connect(SmbTreeConnection.java:460) [jcifs-ng-2.1.0-SNAPSHOT.jar:?]
        at jcifs.smb.SmbTreeConnection.connectWrapException(SmbTreeConnection.java:421) [jcifs-ng-2.1.0-SNAPSHOT.jar:?]
        at jcifs.smb.SmbFile.ensureTreeConnected(SmbFile.java:548) [jcifs-ng-2.1.0-SNAPSHOT.jar:?]
        at jcifs.smb.SmbFile.exists(SmbFile.java:824) [jcifs-ng-2.1.0-SNAPSHOT.jar:?]

**Comment by mbechler** [comment] 2018-02-18 12:25
Okay, I think that the SmbAuthException in 2.0.4 might be masking the same issue, if you have a chance to enable debugging for that, it would be good to verify that you are seeing a response with error code 0xC00000BB before that. 

I suppose that you redacted all the NtlmContext/SpnegoContext values and these are not actually empty, right?

So what seems to happen here is that the server is rejecting our SessionSetup/Authentication request with NT_STATUS_NOT_SUPPORTED, specifically the one with the final NTLM message.

So we need to find out what it is that the custom Hitachi SMB server implementation does not like about our messages. I obviously don't have access to a Hitachi NAS and also they don't seem to have a software simulator - so this may be difficult.

- For 2.1 I added some new SPNEGO/NTLM features, so comparing with 2.0 as noted above should help us telling whether these are the issue. jcifs.smb.useRawNTLM=true may also change something there.
- Have you been using the original jcifs before and it worked? Setting jcifs.smb.client.useExtendedSecurity=false might restore the original behavior.
- Verify that the the login works with samba. If possible compare the SessionSetup requests/responses with each other.

Any chance you can reproduce these with a test user that would allow you to share full debugging info and packet traces?

**Comment by manithree** [comment] 2018-02-18 14:57
Yes, I redacted the NtlmContext/SpnegoContext values.  Dunno if that was necessary, just feeling paranoid, i guess.
Original jcifs is working, and has been for years.  Good news, setting jcifs.smb.client.useExtendedSecurity=false allows jcifs-ng to work.
I'll work on getting a test user created, but that will be a multi-day ticket request and approval process, so it won't be quick.
Thanks for your help so far.

**Comment by mbechler** [comment] 2018-02-18 16:00
Checking again I found that - unlike I remembered - the original jcifs should already have been using extended security by default as well, so this is most likely caused by some change in the NTLMSSP messages exchanged. Until 2.0 there haven't been too many changes in that area and I don't see anything direcly obvious.

If you can verify that 2.0 also has that STATUS_NOT_SUPPORTED error and we are therefor not looking at two distinct issues, that would be appreciated.

Once can provide me with a failing jcifs-ng packet trace and one of a working client (preferrably samba as I have been trying to align the auth behavior with that so far) to compare I hope I should be able to figure that out.

**Comment by mbechler** [comment] 2018-04-15 12:43
Have you had a chance to test whether the fixes work for you, too? Closing this for now, please reopen if not fixed.

**Closed by mbechler** 2018-04-15 12:43 UTC
