### ISSUE TITLE
Connection leak on SMB authentication failure

### ISSUE THREAD

**Issue by romanblachman** [AgNO3/jcifs-ng#191] opened 2019-11-04 20:26 UTC
We are experiencing a connection leak (sockets left open) when SamrPolicyHandle creation fails with SmbAuthException:

```
2019-11-04 19:53:13,602 TRACE 16669 [yRestService-15] jcifs.util.transport.Transport           : Release transport 1 Transport709[hostname.domain.com/172.16.10.97:445,state=3,signingEnforced=true,usage=1]
2019-11-04 19:53:13,602  WARN 16669 [yRestService-15] jcifs.smb.SmbTreeConnection              : Referral failed, trying next

jcifs.smb.SmbAuthException: GSSAPI mechanism failed
	at jcifs.smb.Kerb5Context.initSecContext(Kerb5Context.java:300)
	at jcifs.smb.SpnegoContext.negotitate(SpnegoContext.java:282)
	at jcifs.smb.SpnegoContext.initSecContext(SpnegoContext.java:201)
	at jcifs.smb.SmbSessionImpl$1.run(SmbSessionImpl.java:642)
	at jcifs.smb.SmbSessionImpl$1.run(SmbSessionImpl.java:638)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at jcifs.smb.SmbSessionImpl.createToken(SmbSessionImpl.java:638)
	at jcifs.smb.SmbSessionImpl.sessionSetupSMB2(SmbSessionImpl.java:536)
	at jcifs.smb.SmbSessionImpl.sessionSetup(SmbSessionImpl.java:481)
	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:367)
	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:345)
	at jcifs.smb.SmbTreeImpl.treeConnect(SmbTreeImpl.java:607)
	at jcifs.smb.SmbTreeConnection.connectTree(SmbTreeConnection.java:597)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:551)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:472)
	at jcifs.smb.SmbTreeConnection.connect(SmbTreeConnection.java:448)
	at jcifs.smb.SmbTreeConnection.connectWrapException(SmbTreeConnection.java:409)
	at jcifs.smb.SmbFile.ensureTreeConnected(SmbFile.java:551)
	at jcifs.smb.SmbPipeHandleImpl.ensureTreeConnected(SmbPipeHandleImpl.java:111)
	at jcifs.smb.SmbPipeHandleImpl.ensureOpen(SmbPipeHandleImpl.java:166)
	at jcifs.smb.SmbPipeHandleImpl.sendrecv(SmbPipeHandleImpl.java:250)
	at jcifs.dcerpc.DcerpcPipeHandle.doSendReceiveFragment(DcerpcPipeHandle.java:113)
	at jcifs.dcerpc.DcerpcHandle.sendrecv(DcerpcHandle.java:243)
	at jcifs.dcerpc.DcerpcHandle.bind(DcerpcHandle.java:216)
	at jcifs.dcerpc.DcerpcHandle.sendrecv(DcerpcHandle.java:234)
	at jcifs.dcerpc.msrpc.SamrPolicyHandle.<init>(SamrPolicyHandle.java:45)
```

Other than seeing an open socket when running lsof on the process, the following traces appear in the log every couple of minutes:

```
2019-11-04 20:02:34,099 TRACE 16669 [   Transport709] jcifs.util.transport.Transport           : Socket timeout during peekKey

java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at jcifs.util.transport.Transport.readn(Transport.java:70)
	at jcifs.smb.SmbTransportImpl.peekKey(SmbTransportImpl.java:808)
	at jcifs.util.transport.Transport.loop(Transport.java:420)
	at jcifs.util.transport.Transport.run(Transport.java:762)
	at java.lang.Thread.run(Thread.java:748)

2019-11-04 20:02:34,099 DEBUG 16669 [   Transport709] jcifs.util.transport.Transport           : Transport still in use, no idle timeout Transport709[hostname.domain.com/172.16.10.97:445,state=3,signingEnforced=true,usage=1]
```
[jcifs-ng_connection_leak.txt](https://github.com/AgNO3/jcifs-ng/files/3805942/jcifs-ng_connection_leak.txt)

In the exception handling, we do call the close() on the DcerpcHandle object.

```
        Kerb5Authenticator kerb5Authenticator = getKerbAuthenticator(targetDomain.toUpperCase());

        CIFSContextCredentialWrapper cifsContext = (CIFSContextCredentialWrapper) this.cifsContext.withCredentials(kerb5Authenticator);

        DcerpcHandle dcerpcHandle;
        try
        {
            dcerpcHandle = DcerpcHandle.getHandle("ncacn_np:" + targetEndpoint + "[\\pipe\\samr]", cifsContext);
        }
        catch (Throwable t)
        {
            throw new RuntimeException(t);
        }

        SamrPolicyHandle samrHandle;
        try
        {
            samrHandle = new SamrPolicyHandle(dcerpcHandle, targetEndpoint, samr.SamrServerAccessReadMask);
        }
        catch (Throwable t)
        {
            // Ensure that DCERPC handle is closed, if we are unable to create the SAMR handle
            try
            {
                dcerpcHandle.close();
            }
            catch (IOException ignored)
            {
            }
            throw new RuntimeException(t);
        }
```

Let me know if there is any information we can provide to figure out this issue.

Thank you,
Roman

**Comment by mbechler** [comment] 2019-11-10 15:00
The connection is normally expected to stay open to be reused. You need to reuse the root cifs context to benefit from that, otherwise you need to close the root context (and with it the transport pool). 
Or is this connection not reused when using the same context and a fresh one created every time?

**Comment by EllikoPre** [comment] 2019-11-10 15:39
I'll just add some info - we are creating a lot of connections over time, so we make sure to close them once we finish retrieving the data we need.
We are reusing the same cifsContext each time we create a new DcerpcHandle, and when we're done we close the handle.

The problem is that when we get the exception in the SamrDomainHandle creation, the closing of the DcerpcHandle is not enough, something is leaking.
Should we close the cifsContext as well in this scenario?

**Comment by mbechler** [comment] 2019-11-10 16:16
If you are reusing the cifsContext then you should not have to. 
So this means that the existing connection does not get idle-closed but also it's reuse fails when a new connection to the same target is established after an error ? 
A trace-level log of the error and a follow up connection attempt would be useful.

**Comment by romanblachman** [comment] 2019-11-10 19:52
hello @mbechler, I'm attaching a trace level log of the issue. The connection in the attached log is made to dev-pc01 10.1.0.107 with a wrong Kerberos ticket that causes SmbAuthException (GSSAPI failure) and the socket stays open:

[jcifs_connection_kept_open_trace.log](https://github.com/AgNO3/jcifs-ng/files/3828915/jcifs_connection_kept_open_trace.log)

java    3023 root  328u  IPv6         2984252599      0t0        TCP 10.1.0.9:50484->10.1.0.107:microsoft-ds (ESTABLISHED)

Thank you!

**Comment by mbechler** [comment] 2019-12-01 16:33
Looks like a session leak and therefor connection leak was introduced in the auth retry code whenever the authentication failed. Please try the patch in master.

**Comment by romanblachman** [comment] 2020-06-01 10:56
It worked! Thanks!

**Closed** 2020-06-06 10:04 UTC
