### ISSUE TITLE
NullPointerException on SmbFile.exists

### ISSUE THREAD

**Issue by julienFL** [AgNO3/jcifs-ng#178] opened 2019-07-22 14:18 UTC
Hi, 

I sometimes encounter a NullPointerException using the SmbFile.exists method in version 2.1.2

I can have two different stack traces :
`java.lang.NullPointerException
        at jcifs.smb.SmbSessionImpl.sessionSetupSMB2(SmbSessionImpl.java:520) ~[?:?]
        at jcifs.smb.SmbSessionImpl.sessionSetup(SmbSessionImpl.java:483) ~[?:?]
        at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:369) ~[?:?]
        at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:347) ~[?:?]
        at jcifs.smb.SmbTreeImpl.treeConnect(SmbTreeImpl.java:607) ~[?:?]
        at jcifs.smb.SmbTreeConnection.connectTree(SmbTreeConnection.java:609) ~[?:?]
        at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:563) ~[?:?]
        at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:484) ~[?:?]
        at jcifs.smb.SmbTreeConnection.connect(SmbTreeConnection.java:460) ~[?:?]
        at jcifs.smb.SmbTreeConnection.connectWrapException(SmbTreeConnection.java:421) ~[?:?]
        at jcifs.smb.SmbFile.ensureTreeConnected(SmbFile.java:551) ~[?:?]
        at jcifs.smb.SmbFile.exists(SmbFile.java:838) ~[?:?]`

or : 

java.lang.NullPointerException
        at jcifs.smb.SmbTransportImpl.isSigningEnforced(SmbTransportImpl.java:311) ~[?:?]
        at jcifs.smb.SmbTransportPoolImpl.findConnection(SmbTransportPoolImpl.java:134) ~[?:?]
        at jcifs.smb.SmbTransportPoolImpl.getSmbTransport(SmbTransportPoolImpl.java:195) ~[?:?]
        at jcifs.smb.SmbTransportPoolImpl.getSmbTransport(SmbTransportPoolImpl.java:47) ~[?:?]
        at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:560) ~[?:?]
        at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:484) ~[?:?]
        at jcifs.smb.SmbTreeConnection.connect(SmbTreeConnection.java:460) ~[?:?]
        at jcifs.smb.SmbTreeConnection.connectWrapException(SmbTreeConnection.java:421) ~[?:?]
        at jcifs.smb.SmbFile.ensureTreeConnected(SmbFile.java:551) ~[?:?]
        at jcifs.smb.SmbFile.exists(SmbFile.java:838) ~[?:?]

Sometimes those errors are linked to connection problems to a share, but sometimes not..

Thanks

**Comment by mbechler** [comment] 2019-07-27 07:16
This is ultimmately caused by not having received any negotation data, which means that the connection has not completed. 
So it seems that there might be a situation where we fall through the connect method having a connection and without an exception. Any chance you could get a debug log of when this occurs?

**Comment by f-cramer** [comment] 2019-07-28 22:05
I am having the same problem. Before getting the NullPointerException I get the following error:
```
Exception in thread "Transport1" java.lang.OutOfMemoryError: Java heap space
 at jcifs.smb.SmbTransportImpl.negotiate2(SmbTransportImpl.java:650)
 at jcifs.smb.SmbTransportImpl.negotiate(SmbTransportImpl.java:531)
 at jcifs.smb.SmbTransportImpl.doConnect(SmbTransportImpl.java:702)
 at jcifs.util.transport.Transport.run(Transport.java:732)
 at java.lang.Thread.run(Thread.java:748)
```

This seems to ultimately be caused by the changes in `jcifs.internal.smb2.nego.Smb2NegotiateResponse#readBytesWireFormat` regarding the local variable `ncpos` that were introduced in version 2.1. I can "correct" the error by replacing any occurence of `ncpos` with `bufferIndex` as it was in version 2.0, but obviously I have no real idea why it works and if it breaks other things.

Some additional information:
I am using jcifs-ng as part of a gradle plugin that copies jars and config files to different network shares. Using the current version of jcifs-ng (2.1.3) I can successfully copy all files to any network share that is hosted on a Windows Server 2012 or 2016 machine. If I try to copy the same files to a Windows Server 2008 R2 I get the exception above. Using the 2.0 branch of jcifs-ng (currently version 2.0.8) works for all three servers.

**Comment by julienFL** [comment] 2019-07-29 09:39
> This is ultimmately caused by not having received any negotation data, which means that the connection has not completed.
> So it seems that there might be a situation where we fall through the connect method having a connection and without an exception. Any chance you could get a debug log of when this occurs?

Unfortunately I am surprisingly not able to reproduce the error at this time, but if it happens again I will get the debug log.
I also forgot to mention that it happened with a Windows Server 2008 R2. It may be linked with what mentioned @f-cramer but the difference is that I never get an OOM error.

**Comment by mbechler** [comment] 2019-08-03 10:29
At least for the OOM I think I can see what is going on. The server could return garbage in the negotiate context fields for eariler verisons, we need to check the revision and only parse the contexts if it's 3.11.

**Comment by f-cramer** [comment] 2019-08-03 17:51
I can confirm that the newest commit does _not_ fix the OOE for me. Shouldn't `ncpos` be ignored in the return value as well when parsing negotiation contexts is disabled?

**Comment by Sv3nds3n** [comment] 2020-03-20 13:24
I have encountered the same problem, while accessing a Windows 7 file-share.

As stated earlier, the `ncpos` should most likely _not_ be assigned this "garbage value", as it causes OOM exception later.

A screenshot from my debug-session, illustrating the values. - The `this.dialectRevision` had value 0x02FF at that time.

![jCIFSng_problem-1](https://user-images.githubusercontent.com/62431158/77167246-f0374400-6ab5-11ea-8bf6-f9a2ee50713d.jpg)

**Comment by mbechler** [comment] 2020-03-22 10:10
Sorry, lost track of the previous comment.

**Closed** 2020-07-09 14:49 UTC
