### ISSUE TITLE
The network name cannot be found

### ISSUE THREAD

**Issue by cliviu** [AgNO3/jcifs-ng#78] opened 2018-05-09 14:40 UTC
Hi, I have the following Exception`jcifs.smb.SmbException: The network name cannot be found.
	at jcifs.smb.SmbTransportImpl.checkStatus(SmbTransportImpl.java:1343)
	at jcifs.smb.SmbTransportImpl.checkStatus(SmbTransportImpl.java:1509)
	at jcifs.smb.SmbTransportImpl.sendrecv(SmbTransportImpl.java:980)
	at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1475)
	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:397)
	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:336)
	at jcifs.smb.SmbTreeImpl.treeConnect(SmbTreeImpl.java:600)
	at jcifs.smb.SmbTreeConnection.connectTree(SmbTreeConnection.java:609)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:563)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:484)
	at jcifs.smb.SmbTreeConnection.connect(SmbTreeConnection.java:460)
	at jcifs.smb.SmbTreeConnection.connectWrapException(SmbTreeConnection.java:421)
	at jcifs.smb.SmbFile.ensureTreeConnected(SmbFile.java:545)
	at jcifs.smb.SmbFile.connect(SmbFile.java:504)`
when trying to connect to a DFS Share even if the searched host is available  (responds to ping and the share is visible in WindowsExplorer) .

   Another question will be if this old issue from jcifs is fixed in jcifs-ng : https://lists.samba.org/archive/jcifs/2017-May/010366.html

  Does anybody have a hint for me  ?  Thanks !

**Comment by cliviu** [comment] 2018-05-15 08:28
Any idea ?

**Comment by cliviu** [comment] 2018-05-15 08:29
Is this a known issue ? Any kind of feedback is valuable for me .

**Comment by mbechler** [comment] 2018-05-16 16:19
0xC00000CC is actually BAD_NETWORK_NAME which (modulo some nasty bugs) means that the server does not like beeing called myhost.de.

I would guess that this is a domain DFS and not a standalone one?
Is myhost.de the domain name? Then earlier logs would be interesting, there should be some place were it is trying to look up the domain controllers and dfs roots for the domain and that seems to be failing in some way (hence the "No match for domain based root").

**Comment by cliviu** [comment] 2018-05-17 07:30
Hi, Thanks for looking into this. I attach another log file. Indeed, there is a domain DFS.  "myhost.de" is the domain name. Hope we have not catched one of the nasty bugs :-(. At least will be important to identify it.
[analyse1.txt](https://github.com/AgNO3/jcifs-ng/files/2012042/analyse1.txt).
192.168.8.6 ist pingable 
![ping](https://user-images.githubusercontent.com/2623175/40162666-fb087872-59b4-11e8-8155-234400f53557.png)

**Comment by cliviu** [comment] 2018-05-17 12:57
By the way, do you know what error code is Error code: **0xC000019C** for Trans2GetDfsReferral ?

2018-05-11 12:59:51,879|SmbTransportImpl              |TRACE|FF534D42329C0100C09803C800000000000000000000000000085BF500080400
2018-05-11 12:59:51,889|SmbTransportImpl              |DEBUG|Error code: 0xC000019C for Trans2GetDfsReferral
2018-05-11 12:59:51,890|SmbSessionImpl                |TRACE|Send failed
jcifs.smb.SmbException: 0xC000019C
	at jcifs.smb.SmbTransportImpl.checkStatus(SmbTransportImpl.java:1343)
	at jcifs.smb.SmbTransportImpl.sendComTransaction(SmbTransportImpl.java:1608)
	at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1469)
	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:397)
	at jcifs.smb.SmbTreeImpl.send(SmbTreeImpl.java:465)
	at jcifs.smb.SmbTreeImpl.send(SmbTreeImpl.java:406)
	at jcifs.smb.SmbTransportImpl.getDfsReferrals(SmbTransportImpl.java:1659)
	at jcifs.smb.DfsImpl.getDcReferrals(DfsImpl.java:192)
	at jcifs.smb.DfsImpl.getDc(DfsImpl.java:234)
	at jcifs.smb.DfsImpl.getTrustedDomains(DfsImpl.java:112)
	at jcifs.smb.DfsImpl.resolve(DfsImpl.java:347)
	at jcifs.smb.DfsImpl.resolve(DfsImpl.java:321)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:525)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:484)
	at jcifs.smb.SmbTreeConnection.connect(SmbTreeConnection.java:460)
	at jcifs.smb.SmbTreeConnection.connectWrapException(SmbTreeConnection.java:421)
	at jcifs.smb.SmbFile.ensureTreeConnected(SmbFile.java:545)
	at jcifs.smb.SmbFile.connect(SmbFile.java:504)

**Comment by cliviu** [comment] 2018-05-18 10:05
We are trying to access a domain based DFS which can be accessed in Windows explorer like: \\MyDomainName.com\DFSShareName

When configuring MyDomainName.com as the host name and DFSShareName as the root share with jcifs-ng, the library successfully resolves the names of the domain controllers (probably using DNS). At least the log shows that all IP addresses resolved by a DNS lookup of MyDomainName.com are accessed by the library (SmbTransportPoolImpl subsequently opens a new transport connection for each IP on port 445). On that transport, a SmbComTreeConnectAndX request is sent (to the domain controller?) but is always refused with 0xC00000CC. According to https://msdn.microsoft.com/en-us/library/cc704588.aspx this means “The specified share name cannot be found on the remote server”. The domain controller itself does not provide this share. So if the library tries to access the share on the domain controller itself, this error would be expected. But shouldn’t the library be able to do a “DFS lookup” of the (in our case two) IP addresses of the actual DFS servers like Windows seems to do? What makes us wonder is that the logfile never shows the IP addresses of the two file servers (not domain controllers!) that are providing the DFS share.

The attached log shows this procedure for one of the domain controllers. The logging is the same for all of them.
[forum_log_1.txt](https://github.com/AgNO3/jcifs-ng/files/2016382/forum_log_1.txt)

**Comment by mbechler** [comment] 2018-05-19 08:11
Right. The library should be looking up the domain's DFS roots using RPC with the domain controller somwhere earliert in the exchange (this normally should be the first connection happening).
Can you provide a log from the start?
This lookup is based on the domain of the user account you are using (which is a bit strange I admit and maybe deserves a change) and it's trust relations. I'm seeing MYGROUP there in the logs, is that the same as domain?

**Comment by cliviu** [comment] 2018-05-19 20:54
Here is the complete log. ipaddr3 and ipaddr4 are the domain controllers for MyDomainName.com.
As mentioned before, the ip addresses of the servers holding the shares do not appear in the log file. 
What do you mean by MYGROUP being the same as domain ? 
[forum_log_2.txt](https://github.com/AgNO3/jcifs-ng/files/2019797/forum_log_2.txt)

**Comment by mbechler** [comment] 2018-05-21 09:07
The interesting part is right in the beginning, the client connects to what should be the users domain controller (MYGROUP<1D>/ipaddr1) and tries to determine the domain names available for DFS.

That domain controller responds with 0xC000019C trying to get DFS referrals, which should mean that it does not have DFS support. 

So this seems to be an issue with the way we lookup the DFS roots.

Could you try whether the same thing works when you are using a user account from MyDomainName.com?

I'm not really sure right now how MS is doing that, maybe they would be using the computers domain name to start with - but I guess we should at least add an option to configure an override domain.

**Comment by cliviu** [comment] 2018-05-21 09:31
Thanks, we will try a user account from MyDomainName.com

**Comment by swmgr** [comment] 2018-05-22 08:58
Hi @mbechler. First of all, thanks again for your time, support and advice on this.
I've been working with @cliviu in analyzing and want to share some new findings with you.

- The name MYGROUP (used for the user name) is the NetBIOS name of MyDomainName.com
- ipaddr1 (returning the 0xC000019C status code) is a workstation in the domain that has (as far as we know) nothing to do with the provisioning of the DFS Share. Only relation of this IP to the DFS we can currently know of is that this workstation might be accessing the share (through Windows directly) at times. We currently do not understand why jcifs-ng is trying to access the share on that ip.

Next we are going to test with a user from MyDomainName.com.

**Comment by swmgr** [comment] 2018-05-23 17:21
We've conducted the test with a user name from the domain MyDomainName.com. Unfortunately jcifs still does not resolve the DFS roots, as it seems. All SmbComTreeConnectAndX calls we can see are for the two domain controllers, which will result in error (0xC00000CC as before and new: 0xC00000BD). The two IP addresses of the file servers actually providing the share still do not show up in the log (attached).
[forum_log_3.txt](https://github.com/AgNO3/jcifs-ng/files/2032106/forum_log_3.txt)

Any ideas? Thank you.

**Comment by mbechler** [comment] 2018-05-31 15:32
Both MYGROUP resolving to ipaddr1 and the "A duplicate name exists on the network." error are quite a bit strange. Both are naming related, so I would probably have look in that direction (have a look at the DNS/netbios traffic).

For SMB2 you'll need to set jcifs.smb.client.enableSMB2=true (and for enforcing it also jcifs.smb.client.disableSMB1=true), but I guess that won't make a difference.

**Comment by jonathanmmm** [comment] 2019-01-31 10:04
I have seen different errors in our network.
We have 3 DFS Servers in our Domain and 4 Domain Controllers.
DC1 is also DFS1
DC2 is also DFS2
DC3 and DC4 on location is not a DFS but only a domain Controller.

When I try to access company.local I get the DNS of one of the 4 Domain Controllers.

Then the Domain Controller should give the JCIFS in the Android App (https://github.com/Sentaroh/SMBSync2/) the DFS Root server.

But when the App gets the IP of one of the Domain Controllers without DFS it fails, so it is somehow random.

If I access the DC3 or DC4 via Explorer on Windows and e.g. use DC3\DFSShareUser it works even if the DC3 or DC4 is not a DFS Share. But on the App it does not resolve.

If I access in Windows Explorer \\DC1 I can see DFSShareUser and NETLOGON and SYLVOL and so on.
same with DC2 but on DC3 and DC4 I can only see NETLOGON and SYSVOL (which is ok, they are not a DFS Server, only Domain Controller).

But I can still access the path with \\DC1\DFSShareUser or with \\DC3\DFSShareUser the same without seeing compromises on Windows.

**Comment by svella** [comment] 2019-09-04 19:08
I'm seeing similar issues with a customer where the namespace servers are file servers, not DC's. The only way we've been able to get it to work is to add a hosts file entry that redirects the domain names to the namespace server ip's (which is going to be fragile). Wondering if there is supposed to be another part of the protocol that lets you look up the namespace servers via a connection to the DC. Windows obviously knows how to do it - perhaps it's directly via the directory rather than via SMB?

**Comment by mbechler** [comment] 2019-09-08 10:22
If you have a chance to get a packet capture of a working DFS referral, that would be great. Everything I've seen so far and per documentation, getting the root referral happens through the DC. Maybe there is another reason this fails?

**Comment by svella** [comment] 2019-09-09 12:54
I dug into this yesterday by creating an environment where DC, namespace server, and file server were all on separate EC2 instances and was easily able to reproduce it. It appears that what is missing is a a request to the DC to get a root referral - jcifs-ng is just asking the DC to resolve the whole DFS path rather than asking it to resolve the root, and then asking the root to resolve the whole path (See https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-dfsc/1ff7d611-ba19-49fb-95f4-7c5358b86834). The spec is very vague on this point and apparently smbj had a similar issue (https://github.com/hierynomus/smbj/issues/212)
I'm attaching wireshark pcaps 

- dc-is-namespace-server.pcapng - jcifs-ng when DC is also namespace server (works)
- dc-not-namespace-server.pcapng - jcifs-ng when DC is not namespace server (doesn't work)
- dc-not-namespace-server-win.pcapng - request from the fileserver when DC is not namespace server (does work) - note the request to the DC to resolve the root first and then the request to the root to resolve the path.
[pcaps.zip](https://github.com/AgNO3/jcifs-ng/files/3590556/pcaps.zip)

**Comment by svella** [comment] 2019-09-09 13:05
I'm hoping to get time to look into providing a fix for this myself, but short term am going to try to convince customer to make the DC's namespace servers as well.

**Closed** 2020-03-01 11:49 UTC
